### ISSUE TITLE
Add DataDog to openAPM

### ISSUE THREAD

**Issue by Sandared** [openapm/landscape-model#115]
DD host metrics and main agent https://github.com/DataDog/datadog-agent
Java Tracing https://github.com/DataDog/dd-trace-java
.NET Tracing https://github.com/DataDog/dd-trace-dotnet
PHP Tracing https://github.com/DataDog/dd-trace-php
Ruby Tracing https://github.com/DataDog/dd-trace-rb

**Comment by AlexanderWert** [comment]
Datadog has been added.
