### ISSUE TITLE
Add license information to the components in the model

### ISSUE THREAD

**Issue by ivansenic** [openapm/landscape-model#3]
All components should have license information so that we can display it in the component details.

**Comment by ivansenic** [comment]
@tzwickl any chance you could do this? I know it's a bit boring, but we need to get this done. I think for more of the tools it's quite easy, only some components have some strange licenses.

@AlexanderWert this is important right? or we can also go without this? I am afraid we need to make a decision now, it's already so hard to all the information that's missing already?

**Comment by tzwickl** [comment]
@ivansenic yes I can do that. How should the field be named?
But I should only add license information for the components and not for the connections?

**Comment by ivansenic** [comment]
Yes only for components. Name the field `license`, just under the `description` or `logo`. The value should be a smth we can display immediately, same as the description or website link.

**Comment by ivansenic** [comment]
@tzwickl You can list both licenses 

`- license: Apache License 2.0, Elastic License`

As said this is just a text going to be directly printed on the website,

**Comment by AlexanderWert** [comment]
I would prefer that license is always a list of license-names, instead of a comma-seperated text. This makes it easier for later improvement (e.g. showing licenses as links to the license texts, etc.).
