### ISSUE TITLE
Add AppDash

### ISSUE THREAD

**Issue by AlexanderWert** [openapm/landscape-model#44]
Hi @slimsag, hi @chris-ramon,

would you be interested in adding AppDash to the OpenAPM landscape: https://openapm.io/landscape ?

I would love to see AppDash being part of this landscape!

Contributing is easy: just submit a corresponding yml file in this repository.
More: https://github.com/openapm/landscape-model/blob/master/CONTRIBUTE.md

Thanks!
Alex

**Comment by slimsag** [comment]
Hi,

We're not actively working on / using Appdash in production anymore -- but certainly feel free to mention it here if you like. :)

Also, you might like http://opentracing.io/ and its implementations such as Lightstep (see http://opentracing.io/documentation/pages/supported-tracers.html).

(side note: I can't really tell from openapm.io what it provides, if anything; is it just a site linking to a bunch of open source perf monitoring projects?)

**Comment by AlexanderWert** [comment]
Hi @slimsag ,

thank you for your quick response and the feedback!

The goal of OpenAPM is to give an overview on open source possibilities wrt. APM.
In particular, it shows which different APM-related open source tools can be combined / integrated to achieve more comprehensive APM solutions!

Regards,
Alex

**Comment by ivansenic** [comment]
@slimsag Isn't Lightstep a commercial product? I mean, I know that their agents are open-source, but you do need a `APP KEY` in order to use it? And to get `APP KEY` you need to pay right? Or am I missing something?

**Comment by AlexanderWert** [comment]
AppDash is not maintained anymore
