### ISSUE TITLE
Add AppMetrics

### ISSUE THREAD

**Issue by AlexanderWert** [openapm/landscape-model#45]
https://github.com/AppMetrics/AppMetrics

**Comment by AlexanderWert** [comment]
Hi @alhardy, 

interested in providing a yml file for this?
Would appreciate your contribution!

**Comment by alhardy** [comment]
Been meaning to get to this, it is on my todo list. Will throw it in sometime over the next few days. 

Thanks for the mention 👍

**Comment by AlexanderWert** [comment]
@alhardy Thanks a lot!
