### ISSUE TITLE
OpenAPM Badge for Icinga Homepage

### ISSUE THREAD

**Issue by AlexanderWert** [openapm/landscape-model#66]
Hi @bobapple,

thanks again for contributing Icinga to the OpenAPM landscape!
For the tools enriching the OpenAPM landscape we provide a Badge (see example at the bottom of https://inspectit.rocks).

We would love and really appreciate to see such a badge also on the Icinga homepage!
Do you think this is possible? Can I provide you an HTML snippet for the Icinga homepage?

Thanks you!

Regards,
Alex

**Comment by bobapple** [comment]
Hi @AlexanderWert 

we currently don't really have a section for badges and similar on the website. I can offer you to publish a blogpost on this topic?

Best
Blerim

**Comment by AlexanderWert** [comment]
Hi @bobapple,

thanks for the reply! I just though the badge maybe would fit below the "Our Customers" section.

But a blog post would also be great! Thanks for the offer!
What information would you need from me for the blog post? I will provide it to you.

Thanks!

Alex
